project:
  type: website
  output-dir: docs

website:
  favicon: favicon.ico
  search:
    location: navbar
    type: overlay
  navbar:
    title: professional profile
    logo: resources\logo.png
  page-footer:
    right: "Egbert &copy; 2023"
    center:
      - icon: envelope-fill
        href: mailto:w.brett.egbert@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/w-brett-egbert/
      # - icon: patch-check-fill
      #   href: https://www.credly.com/users/brett-egbert
      - icon: github
        href: https://github.com/crossinguard

format:
  html:
    theme: scss\cg-dark.scss
    link-external-icon: false
    link-external-newwindow: true
    anchor-sections: false
    reference-location: margin
