---
toc: true
toc-depth: 2
title: Egbert | professional profile
---

::::: {#intro}

**W. Brett Egbert**

::: {#roles}

business analyst, assessment developer, mathematics educator

:::

---

::: {#social .d-flex .gap-4}

[<i class="bi bi-envelope-fill"></i>](mailto:w.brett.egbert@gmail.com)

[<i class="bi bi-linkedin"></i>](https://www.linkedin.com/in/w-brett-egbert/)

[<i class="bi bi-github"></i>](https://github.com/crossinguard)

[<i class="bi bi-award-fill"></i>](https://www.credly.com/users/brett-egbert)

:::

[[<i class="bi bi-chevron-down"></i> see my work]{.btn .btn-outline-primary .btn-lg}](#portfolio)

:::::

## about me

### <i class="bi bi-rewind-btn-fill"></i><br>past

I began my professional career as a secondary-level mathematics instructor in Alpine School District, UT. During my eight year tenure I taught algebra, statistics, geometry, and calculus to adolescent learners, specializing in those that historically "disagreed" with math. In addition to serving as the mathematics department chair for three years, I coached the school's first esports team in their inaugural season of Rocket League. **Go Falcons!**

I next joined the remote workforce as a capstone evaluator for learners within WGU's mathematics education programs. A renewed interest in computer science led to my transition into program development for the College of IT where I designed innovative summative assessments for fundamental coding courses (e.g., Python, SQL, Java). Concurrently, I earned a data analytics degree to complement my mathematics background.

At the start of 2023 I joined the profession of analytics as a business analyst with WGU's Service Design and Innovation administrative team, tasked with creating alternative pathways for WGU's prospective students. I explored data and built custom executive reports & dashboards to provide atypical reporting on WGU initiatives. I collaborated with project managers, directors, deans, vice-presidents, and other data professionals to provide ad-hoc analytics with quickly evolving priorities. 

### <i class="bi bi-play-btn-fill"></i><br>present

I am an analyst & educator, highly skilled in the bidirectional transfer of knowledge with stakeholders of diverse backgrounds, technical knowledge, and age groups. I specialize in defining surrounding knowledge & processes while promoting an atmosphere of shared understanding. 

### <i class="bi bi-fast-forward-btn-fill"></i><br>future

Unfortunately, a 2023 reduction in staff led to layoffs for the majority of my team at WGU, myself included. I am currently seeking a new opportunity to apply my skills and experience in a new environment. I excel at learning new tools & processes, am hungry to improve, and have the technical skill to not just identify issues but to implement solutions. 

## skills

::: {#analytics-card .skills-cards}

### <i class="bi bi-clipboard-data-fill"></i></br>analytics

Compile & generate insights from data to drive business decisions through ad-hoc reports and business intelligence executive dashboards.

<span class="badge bg-warning">analytics</span>

:::

::: {#process-mapping-card .skills-cards}

### <i class="bi bi-signpost-2-fill"></i></br>process mapping

Define & document processes to increase consistency while improving workflows for atypical pathways.

<span class="badge bg-info">process mapping</span>

:::

::: {#transfer-of-knowledge-card .skills-cards}

### <i class="bi bi-share-fill"></i></br>transfer of knowledge

Acquire & convey complex information effectively to stakeholders of diverse technical and knowledge backgrounds. 

<span class="badge bg-success">transfer of knowledge</span>

:::


## curriculum vitae

View my curriculum vitae^[keywords: cv, resume] by selecting one of the options below.

::: {.cv-cards .d-flex}

[[<i class="bi bi-filetype-html"></i> view online]{.btn .btn-outline-secondary}](https://crossinguard.github.io/cv/)

[[<i class="bi bi-filetype-pdf"></i> download file]{.btn .btn-outline-secondary}](resources\egbert-resume.pdf)

:::

## portfolio

::::: {#netflix-card .portfolio-cards}

::: {.portfolio-header}

### Netflix Content Analysis

- [<i class="bi bi-globe2"></i> project website](https://crossinguard.github.io/netflix-content-analysis/)
- [<i class="bi bi-github"></i> github repo](https://github.com/crossinguard/netflix-content-analysis)

:::

::: {.portfolio-badges}

<span class="badge bg-warning">analytics</span>
<span class="badge bg-info">process mapping</span>
<span class="badge bg-success">transfer of knowledge</span>
<span class="badge bg-secondary">Quarto</span>
<span class="badge bg-secondary">R//tidyverse</span>
<span class="badge bg-secondary">Markdown</span>
<span class="badge bg-secondary">CSS</span>
<span class="badge bg-secondary">Sass</span>
<span class="badge bg-secondary">Bootstrap</span>
<span class="badge bg-secondary">Tableau</span>
<span class="badge bg-secondary">csv datasource</span>

:::

*Accompanying Tableau dashboard coming soon!*

#### About

Preparation of Netflix data for use in a Tableau dashboard. Data quality issues regarding columns with multi-value elements, incorrect datatypes & date formats, misplaced values, and column splitting were addressed during this process. 

The resulting clean data was exported to use in a Tableau dashboard for further analysis. The following are sample business questions that could be examined using this dashboard.

1. *How has the average duration of movies and TV shows on Netflix evolved each decade (by release year)?*
2. *Are there certain months when more content is added to Netflix? Does that differ between content types?*
3. *What is the distribution of content by ratings (e.g., PG, PG-13, R)? Does that vary by country of origin?*

#### Tools

A [Quarto](https://quarto.org/) `.qmd` technical document, which employs markdown and functional code blocks similar to a [Jupyter](https://jupyter.org/) coding notebook, was created within [VS Code](https://code.visualstudio.com/). A `csv` file of data was imported as a dataframe/tibble using [R](https://www.r-project.org/) and the [tidyverse](https://www.tidyverse.org/) collection of data science packages.

At the conclusion of the data preparation process, multiple clean `csv` files were exported for use as datasources in a [Tableau Public](https://public.tableau.com/) dashboard. [Pandoc](https://pandoc.org/) was then used to convert the markdown-based `.qmd` document into an HTML file, with custom styling occurring through [Sass](https://sass-lang.com/) with CSS and [Bootstrap](https://getbootstrap.com/). The end result is a human-readable source document that is highly adaptable and cabable of displaying complex information. 

:::::

::::: {#recipe-card .portfolio-cards}

::: {.portfolio-header}

### Recipe Book

- [<i class="bi bi-globe2"></i> project website](https://crossinguard.github.io/recipe-book/)
- [<i class="bi bi-github"></i> github repo](https://github.com/crossinguard/recipe-book)

:::

::: {.portfolio-badges}

<span class="badge bg-info">process mapping</span>
<span class="badge bg-success">transfer of knowledge</span>
<span class="badge bg-secondary">Quarto</span>
<span class="badge bg-secondary">Markdown</span>
<span class="badge bg-secondary">CSS</span>
<span class="badge bg-secondary">Sass</span>
<span class="badge bg-secondary">Bootstrap</span>

:::

#### About

Digital recipe book for personal use. Original and adapted recipes were rewritten from the ground up to emphasize clarity of instructions and ease of use while cooking. 

#### Tools

A [Quarto](https://quarto.org/) `.qmd` technical document, which employs markdown and functional code blocks similar to a [Jupyter](https://jupyter.org/) coding notebook, was created within [VS Code](https://code.visualstudio.com/). [Pandoc](https://pandoc.org/) was then used to convert the markdown-based `.qmd` document into an HTML file, with custom styling occurring through [Sass](https://sass-lang.com/) with CSS and [Bootstrap](https://getbootstrap.com/). The end result is a human-readable source document that is highly adaptable and cabable of displaying complex information. 

:::::

::: {#coming-soon}
Portfolio under construction, more projects coming soon!
:::